### PR TITLE
Improve html removal and rendering of & instead of &amp;

### PR DESCRIPTION
**Pull request by tonypartridge**

### CODE REVIEW

**Comment by PhocaCz** [comment]
Hi, did you test version 3.1.6:
https://github.com/PhocaCz/PhocaOpenGraphPlugin/releases

It should be Ok there (not sure if you read the twitter message but it was released 7 days ago and waited for your testing :-) )

Please test and let me know so I can release it officially.

**Comment by PhocaCz** [comment]
Anyway, I didn't use:
 `htmlspecialchars($value, ENT_QUOTES, 'UTF-8');`

but:
` htmlspecialchars($value, ENT_COMPAT, 'UTF-8');`

ENT_COMPAT should be used in Joomla! 4 (if I have the right information), so will be great if you can test with "ENT_COMPAT" so it is ready for Joomla! 4.

Jan

**Comment by tonypartridge** [comment]
Yes I did, it fails because it renders encoded HTML in the descriptions

I'll update the PR

**Comment by tonypartridge** [comment]
Updated :D

**Comment by PhocaCz** [comment]
Please, test 3.1.7. Should be Ok now.
https://github.com/PhocaCz/PhocaOpenGraphPlugin/releases/download/3.1.7/plg_content_phocaopengraph_v3.1.7.zip
Thank you.

**Comment by tonypartridge** [comment]
Something isn’t quite right & is back as &amp; I’ll run tests tomorrow and commit a fix correctly.

**Pull request merged**
